version: '2'

services:
    reverseproxy:
        depends_on:
            - java
        image: proxy
        ports:
            - "80:80"
        restart: always

    java:
        image: hello:latest
        restart: always
